name: stay_indie
description: "A professional social media platform for indie artists and creators."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  supabase_flutter: ^2.3.4
  timeago: ^3.6.1
  modal_bottom_sheet: ^3.0.0
  flutter_form_builder: ^9.2.1
  image_picker: ^1.0.7
  easy_image_viewer: ^1.4.1
  font_awesome_flutter: ^10.7.0
  im_stepper: ^1.0.1+1
  # im_stepper: 
  #   git:
  #     url: https://github.com/isaacngggg/gr_package_im_stepper.git
  #     ref: master
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  go_router: ^14.1.3
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^5.1.1
  http: ^1.2.1
  webview_flutter: ^4.7.0
  flutter_login_facebook: ^2.0.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.1.0
  firebase_core: ^2.31.1
  expandable_text: ^2.3.0
  flex_color_picker: ^3.4.1
  keyboard_emoji_picker: ^1.0.3
  flutter_riverpod: ^2.5.1
  googleapis: ^13.1.0
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  spotify: ^0.13.6+1
  youtube_player_flutter: ^9.0.1
  youtube_shorts: ^4.0.2
  share_plus: ^9.0.0
  flutter_background_service: ^5.0.5
  flutter_image_compress: ^2.3.0


  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/socialIcons/
