name: stay_indie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  introduction_screen: ^3.1.12
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  supabase_flutter: ^2.3.4
  timeago: ^3.6.1
  modal_bottom_sheet: ^3.0.0
  flutter_form_builder: ^9.2.1
  image_picker: ^1.0.7
  easy_image_viewer: ^1.4.1
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  im_stepper: ^1.0.1+1
  uuid: ^3.0.5
  easy_stepper: ^0.8.3
  google_fonts: ^6.2.1
  go_router: ^13.2.2
  pretty_qr_code: ^3.3.0
  qr_bar_code_scanner_dialog: ^0.0.5
  mobile_scanner: ^4.0.1
  http: ^1.2.1
  webview_flutter: ^4.7.0
  flutter_login_facebook: ^2.0.0
  oauth2: ^2.0.2
  vertical_scrollable_tabview: ^0.1.1
  indexed_list_view: ^3.0.2
  loading_animation_widget: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/socialIcons/
