// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt345tcPHlv6bw-3_ASjb-uUf46nnwMu4',
    appId: '1:302282236965:web:18bd59fd9b66a4ce3f8bcc',
    messagingSenderId: '302282236965',
    projectId: 'greenroom-62b0b',
    authDomain: 'greenroom-62b0b.firebaseapp.com',
    storageBucket: 'greenroom-62b0b.appspot.com',
    measurementId: 'G-6095SSCM2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVySmNdPMqJ1KILEqGKgl2ZmhxZr_ySWU',
    appId: '1:302282236965:android:b284bf469aec40bb3f8bcc',
    messagingSenderId: '302282236965',
    projectId: 'greenroom-62b0b',
    storageBucket: 'greenroom-62b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVI4uHNv-8xJdcZi3DlxouJj0Kq9DKv5U',
    appId: '1:302282236965:ios:36e4be4cc8c7c29f3f8bcc',
    messagingSenderId: '302282236965',
    projectId: 'greenroom-62b0b',
    storageBucket: 'greenroom-62b0b.appspot.com',
    iosBundleId: 'co.uk.isaacng.Indiego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVI4uHNv-8xJdcZi3DlxouJj0Kq9DKv5U',
    appId: '1:302282236965:ios:3ccd0f1ca25461f23f8bcc',
    messagingSenderId: '302282236965',
    projectId: 'greenroom-62b0b',
    storageBucket: 'greenroom-62b0b.appspot.com',
    iosBundleId: 'com.example.stayIndie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt345tcPHlv6bw-3_ASjb-uUf46nnwMu4',
    appId: '1:302282236965:web:c8016879ed9ec7573f8bcc',
    messagingSenderId: '302282236965',
    projectId: 'greenroom-62b0b',
    authDomain: 'greenroom-62b0b.firebaseapp.com',
    storageBucket: 'greenroom-62b0b.appspot.com',
    measurementId: 'G-8X8C9QL9QQ',
  );
}
